### ISSUE TITLE
Plugin not functioning

### ISSUE THREAD

**Issue by JosiahParry** [scandio/jekyll-paginate-multiple#1]
I currently have the following code in my `_config.yml`:
```
paginate_multiple:
  - paginate: 5
    paginate_path: '/blog/page:num'
    sub_dir: '/all'
  - paginate: 5
    paginate_path: '/page:num'
    sub_dir: '/all'
```
With my folder structure from the root: `_posts/all/... .md`

None of the pages paginate. The previous set up was: 
```
paginate_path: "blog/page:num"
paginate: 5
```
This worked but now it does't. I also tried all combinations of leading and ending `"/"`.
